server:
  port: 9501

spring:
  webdb:
    datasource:
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      jdbcUrl: jdbc:sqlserver://192.168.164.134:1433;databaseName=WebDB
      username: SA
      password: Wlgur145!

myId: jkl410907

---

spring:
  profiles: dev
  application:
    name: web-server
    version: v1.0

---